version: '3'
services:

  webserver:
    build: ./build/nginx-certbot
    image: local/nginx-certbot
    container_name: nginx-certbot
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/html:/usr/share/nginx/html:ro
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  webmail:
    build: ./build/roundcube
    image: local/roundcube
    container_name: roundcube
    volumes:
      - ./config/roundcube:/var/roundcube/config:ro
      - ./data/roundcube:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://outlook.office365.com
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp.office365.com

  carddav:
    build: ./build/radicale
    image: local/radicale
    container_name: radicale
    volumes:
      - ./config/radicale:/var/radicale/config:ro
      - ./data/radicale:/var/radicale/data
