version: '3'
services:
  webserver:
    build: ./build
    container_name: nginx-proxy
    volumes:
      - ./data/html:/usr/share/nginx/html:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/log/letsencrypt:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
