version: '3'
services:
  webserver:
    build: ./build
    container_name: nginx-certbot
    volumes:
      - ./data/html:/usr/share/nginx/html:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/log/letsencrypt:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  webmail:
    image: nginx:alpine # For testing purposes
    container_name: roundcube
    volumes:
      - ./data/roundcube/html:/usr/share/nginx/html:ro

  carddav:
    image: nginx:alpine # For testing purposes
    container_name: radicale
    volumes:
      - ./data/radicale:/usr/share/nginx/html:ro
